#!/usr/bin/env bash
# Set proper locale
export LC_ALL='C'

# Default variables for input
DICTIONARY="${DICTIONARY:=./sorted.words}"

# Filter sorted.words properly and output to new file
tr -cs 'A-Za-z' '[\n*]' < $DICTIONARY | sort -u > ./newsorted.words

# Compare stdin to newly filtered dictionary 
tr -cs 'A-Za-z' '[\n*]' < /dev/stdin | sort -u | comm -23 - ./newsorted.words
