#!/bin/sh

# SETUP
## set proper file encoding
export LC_ALL=en_US.UTF-8
## Copy immutable viminfo files to temporary directory
cp ./vimscriptbk/* ./vimscript/
chmod 777 ./vimscript/*
## Download hwk html file
curl -o ./scratchwork/exer1.html https://web.cs.ucla.edu/classes/winter23/cs35L/assign/assign1.html
## make necessary copies
cp ./scratchwork/exer1.html ./scratchwork/exer2.html
cp ./scratchwork/exer1.html ./scratchwork/exer3.html 

executeRegister() {
    /usr/bin/vim -N -u NONE -n -T dumb ./scratchwork/exer"$1".html -i ./vimscript/lab"$1".vim -c "silent! @u" -c "wq" 2>&-
}

diffOrigin() {
    diff -u ./scratchwork/exer1.html ./scratchwork/exer"$1".html > ./scratchwork/exer"$1".diff 
}

# Simulate file edits
## Run recorded commands for lab 1.1
executeRegister 1
## Run recorded commands for lab 1.2
executeRegister 2
## output diff to file
diffOrigin 2
## Run recorded commands for lab 1.3
executeRegister 3
## output diff to check changes
diffOrigin 3
## create exer4.html
cat ./scratchwork/exer2.html ./scratchwork/exer2.diff > ./scratchwork/exer4.html
## Run recorded commands for lab 1.4
executeRegister 4
## Check diff output
diffOrigin 4

# Cleanup
rm -r ./vimscript/* 
# rm -r ./scratchwork/*
